### ISSUE TITLE
"rake appmap" tries to run a removed test if it think the test has changed

### ISSUE THREAD

**Issue by kgilpin** [applandinc/appmap-ruby#216]
```
Removed test files : spec/models/scanner_spec.rb spec/requests/sessions_controller_spec.rb
Changed test files : spec/requests/api_application_finding_status_spec.rb spec/requests/api_scanner_jobs_create_spec.rb spec/requests/scanner_jobs_spec.rb spec/system/scanner_job_spec.rb spec/requests/scenario_uploads_create_spec.rb
Running tests: spec/models/mapset_build_spec.rb spec/models/mapset_cache_spec.rb spec/models/mapset_spec.rb spec/models/scanner_checks_spec.rb spec/models/scanner_finding_spec.rb spec/models/scanner_job_spec.rb spec/models/scanner_spec.rb spec/models/web_resources_spec.rb spec/requests/api_application_finding_status_spec.rb spec/requests/api_appmap_show_spec.rb spec/requests/api_appmaps_create_spec.rb spec/requests/api_appmaps_create_upload_spec.rb spec/requests/api_appmaps_search_spec.rb spec/requests/api_mapsets_create_spec.rb spec/requests/api_mapsets_search_spec.rb spec/requests/api_scanner_jobs_create_spec.rb spec/requests/api_scenarios_create_spec.rb spec/requests/api_scenarios_search_spec.rb spec/requests/application_component_diagram_spec.rb spec/requests/application_related_scenarios_spec.rb spec/requests/application_scenarios_list_spec.rb spec/requests/application_show_spec.rb spec/requests/application_update_spec.rb spec/requests/compare_spec.rb spec/requests/oauth_authentication_spec.rb spec/requests/profile_filters_spec.rb spec/requests/scanner_jobs_spec.rb spec/requests/scenario_destroy_spec.rb spec/requests/scenario_download_spec.rb spec/requests/scenario_show_spec.rb spec/requests/scenario_uploads_create_spec.rb spec/requests/sessions_controller_spec.rb spec/requests/user_show_spec.rb spec/system/api_keys_spec.rb spec/system/application_spec.rb spec/system/applications_spec.rb spec/system/code_stats_spec.rb spec/system/compare_spec.rb spec/system/examples_spec.rb spec/system/explore_spec.rb spec/system/key_data_stats_spec.rb spec/system/login_spec.rb spec/system/org_invitation_spec.rb spec/system/organizations_spec.rb spec/system/recording_method_spec.rb spec/system/scanner_job_spec.rb spec/system/scenario_list_spec.rb spec/system/scenario_properties_spec.rb spec/system/scenario_save_as_spec.rb spec/system/uploading_by_ext_spec.rb spec/system/uploading_data_spec.rb spec/system/uploading_manually_spec.rb spec/system/user_spec.rb spec/system/web_resources_spec.rb
```

```
An error occurred while loading ./spec/requests/sessions_controller_spec.rb. - Did you mean?
                    rspec ./spec/requests/scenario_destroy_spec.rb

Failure/Error: return load_without_bootsnap(resolved, wrap)

LoadError:
  cannot load such file -- /Users/kgilpin/source/appland/appland/spec/requests/sessions_controller_spec.rb
# /Users/kgilpin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
# /Users/kgilpin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
# /Users/kgilpin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:326:in `block in load'
# /Users/kgilpin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
```

**Comment by kgilpin** [comment]
`rake appmap` is deprecated.
